// Generated by tools/generate-android-input-values.py. Do not edit.
package io.nativekit;

import androidx.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/** Stable Java names for input values carried across JNI. */
final class NativeKitInputValues {
    static final int INPUT_RELEASE = 0;
    static final int INPUT_PRESS = 1;
    static final int INPUT_REPEAT = 2;

    @IntDef({INPUT_RELEASE, INPUT_PRESS, INPUT_REPEAT})
    @Retention(RetentionPolicy.SOURCE)
    @interface InputAction {}

    static final int MOD_SHIFT = 1;
    static final int MOD_CONTROL = 2;
    static final int MOD_ALT = 4;
    static final int MOD_SUPER = 8;
    static final int MOD_CAPS_LOCK = 16;
    static final int MOD_NUM_LOCK = 32;

    @IntDef(flag = true, value = {MOD_SHIFT, MOD_CONTROL, MOD_ALT, MOD_SUPER, MOD_CAPS_LOCK,
            MOD_NUM_LOCK})
    @Retention(RetentionPolicy.SOURCE)
    @interface Modifiers {}

    static final int KEY_UNKNOWN = 0;
    static final int KEY_SPACE = 32;
    static final int KEY_APOSTROPHE = 39;
    static final int KEY_COMMA = 44;
    static final int KEY_MINUS = 45;
    static final int KEY_PERIOD = 46;
    static final int KEY_SLASH = 47;
    static final int KEY_0 = 48;
    static final int KEY_1 = 49;
    static final int KEY_2 = 50;
    static final int KEY_3 = 51;
    static final int KEY_4 = 52;
    static final int KEY_5 = 53;
    static final int KEY_6 = 54;
    static final int KEY_7 = 55;
    static final int KEY_8 = 56;
    static final int KEY_9 = 57;
    static final int KEY_SEMICOLON = 59;
    static final int KEY_EQUAL = 61;
    static final int KEY_A = 65;
    static final int KEY_B = 66;
    static final int KEY_C = 67;
    static final int KEY_D = 68;
    static final int KEY_E = 69;
    static final int KEY_F = 70;
    static final int KEY_G = 71;
    static final int KEY_H = 72;
    static final int KEY_I = 73;
    static final int KEY_J = 74;
    static final int KEY_K = 75;
    static final int KEY_L = 76;
    static final int KEY_M = 77;
    static final int KEY_N = 78;
    static final int KEY_O = 79;
    static final int KEY_P = 80;
    static final int KEY_Q = 81;
    static final int KEY_R = 82;
    static final int KEY_S = 83;
    static final int KEY_T = 84;
    static final int KEY_U = 85;
    static final int KEY_V = 86;
    static final int KEY_W = 87;
    static final int KEY_X = 88;
    static final int KEY_Y = 89;
    static final int KEY_Z = 90;
    static final int KEY_LEFT_BRACKET = 91;
    static final int KEY_BACKSLASH = 92;
    static final int KEY_RIGHT_BRACKET = 93;
    static final int KEY_GRAVE_ACCENT = 96;
    static final int KEY_ESCAPE = 256;
    static final int KEY_ENTER = 257;
    static final int KEY_TAB = 258;
    static final int KEY_BACKSPACE = 259;
    static final int KEY_INSERT = 260;
    static final int KEY_DELETE = 261;
    static final int KEY_RIGHT = 262;
    static final int KEY_LEFT = 263;
    static final int KEY_DOWN = 264;
    static final int KEY_UP = 265;
    static final int KEY_PAGE_UP = 266;
    static final int KEY_PAGE_DOWN = 267;
    static final int KEY_HOME = 268;
    static final int KEY_END = 269;
    static final int KEY_CAPS_LOCK = 280;
    static final int KEY_SCROLL_LOCK = 281;
    static final int KEY_NUM_LOCK = 282;
    static final int KEY_PRINT_SCREEN = 283;
    static final int KEY_PAUSE = 284;
    static final int KEY_F1 = 290;
    static final int KEY_F12 = 301;
    static final int KEY_F13 = 302;
    static final int KEY_F14 = 303;
    static final int KEY_F15 = 304;
    static final int KEY_F16 = 305;
    static final int KEY_F17 = 306;
    static final int KEY_F18 = 307;
    static final int KEY_F19 = 308;
    static final int KEY_F20 = 309;
    static final int KEY_F21 = 310;
    static final int KEY_F22 = 311;
    static final int KEY_F23 = 312;
    static final int KEY_F24 = 313;
    static final int KEY_F25 = 314;
    static final int KEY_KP_0 = 320;
    static final int KEY_KP_1 = 321;
    static final int KEY_KP_2 = 322;
    static final int KEY_KP_3 = 323;
    static final int KEY_KP_4 = 324;
    static final int KEY_KP_5 = 325;
    static final int KEY_KP_6 = 326;
    static final int KEY_KP_7 = 327;
    static final int KEY_KP_8 = 328;
    static final int KEY_KP_9 = 329;
    static final int KEY_KP_DECIMAL = 330;
    static final int KEY_KP_DIVIDE = 331;
    static final int KEY_KP_MULTIPLY = 332;
    static final int KEY_KP_SUBTRACT = 333;
    static final int KEY_KP_ADD = 334;
    static final int KEY_KP_ENTER = 335;
    static final int KEY_KP_EQUAL = 336;
    static final int KEY_LEFT_SHIFT = 340;
    static final int KEY_LEFT_CONTROL = 341;
    static final int KEY_LEFT_ALT = 342;
    static final int KEY_LEFT_SUPER = 343;
    static final int KEY_RIGHT_SHIFT = 344;
    static final int KEY_RIGHT_CONTROL = 345;
    static final int KEY_RIGHT_ALT = 346;
    static final int KEY_RIGHT_SUPER = 347;
    static final int KEY_MENU = 348;
    static final int KEY_LAST = 348;

    @IntDef({KEY_UNKNOWN, KEY_SPACE, KEY_APOSTROPHE, KEY_COMMA, KEY_MINUS, KEY_PERIOD, KEY_SLASH,
            KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_SEMICOLON,
            KEY_EQUAL, KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, KEY_H, KEY_I, KEY_J, KEY_K,
            KEY_L, KEY_M, KEY_N, KEY_O, KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T, KEY_U, KEY_V, KEY_W,
            KEY_X, KEY_Y, KEY_Z, KEY_LEFT_BRACKET, KEY_BACKSLASH, KEY_RIGHT_BRACKET,
            KEY_GRAVE_ACCENT, KEY_ESCAPE, KEY_ENTER, KEY_TAB, KEY_BACKSPACE, KEY_INSERT,
            KEY_DELETE, KEY_RIGHT, KEY_LEFT, KEY_DOWN, KEY_UP, KEY_PAGE_UP, KEY_PAGE_DOWN,
            KEY_HOME, KEY_END, KEY_CAPS_LOCK, KEY_SCROLL_LOCK, KEY_NUM_LOCK, KEY_PRINT_SCREEN,
            KEY_PAUSE, KEY_F1, KEY_F12, KEY_F13, KEY_F14, KEY_F15, KEY_F16, KEY_F17, KEY_F18,
            KEY_F19, KEY_F20, KEY_F21, KEY_F22, KEY_F23, KEY_F24, KEY_F25, KEY_KP_0, KEY_KP_1,
            KEY_KP_2, KEY_KP_3, KEY_KP_4, KEY_KP_5, KEY_KP_6, KEY_KP_7, KEY_KP_8, KEY_KP_9,
            KEY_KP_DECIMAL, KEY_KP_DIVIDE, KEY_KP_MULTIPLY, KEY_KP_SUBTRACT, KEY_KP_ADD,
            KEY_KP_ENTER, KEY_KP_EQUAL, KEY_LEFT_SHIFT, KEY_LEFT_CONTROL, KEY_LEFT_ALT,
            KEY_LEFT_SUPER, KEY_RIGHT_SHIFT, KEY_RIGHT_CONTROL, KEY_RIGHT_ALT, KEY_RIGHT_SUPER,
            KEY_MENU, KEY_LAST})
    @Retention(RetentionPolicy.SOURCE)
    @interface Key {}

    static final int POINTER_BUTTON_LEFT = 0;
    static final int POINTER_BUTTON_RIGHT = 1;
    static final int POINTER_BUTTON_MIDDLE = 2;
    static final int POINTER_BUTTON_4 = 3;
    static final int POINTER_BUTTON_5 = 4;
    static final int POINTER_BUTTON_LAST = 7;

    @IntDef({POINTER_BUTTON_LEFT, POINTER_BUTTON_RIGHT, POINTER_BUTTON_MIDDLE, POINTER_BUTTON_4,
            POINTER_BUTTON_5, POINTER_BUTTON_LAST})
    @Retention(RetentionPolicy.SOURCE)
    @interface PointerButton {}

    static final int TOUCH_BEGIN = 1;
    static final int TOUCH_MOVE = 2;
    static final int TOUCH_END = 3;
    static final int TOUCH_CANCEL = 4;

    @IntDef({TOUCH_BEGIN, TOUCH_MOVE, TOUCH_END, TOUCH_CANCEL})
    @Retention(RetentionPolicy.SOURCE)
    @interface TouchAction {}

    static final int TOUCH_TOOL_FINGER = 1;
    static final int TOUCH_TOOL_STYLUS = 2;
    static final int TOUCH_TOOL_ERASER = 3;

    @IntDef({TOUCH_TOOL_FINGER, TOUCH_TOOL_STYLUS, TOUCH_TOOL_ERASER})
    @Retention(RetentionPolicy.SOURCE)
    @interface TouchTool {}

    static final int GAMEPAD_BUTTON_A = 0;
    static final int GAMEPAD_BUTTON_B = 1;
    static final int GAMEPAD_BUTTON_X = 2;
    static final int GAMEPAD_BUTTON_Y = 3;
    static final int GAMEPAD_BUTTON_LEFT_BUMPER = 4;
    static final int GAMEPAD_BUTTON_RIGHT_BUMPER = 5;
    static final int GAMEPAD_BUTTON_BACK = 6;
    static final int GAMEPAD_BUTTON_START = 7;
    static final int GAMEPAD_BUTTON_GUIDE = 8;
    static final int GAMEPAD_BUTTON_LEFT_THUMB = 9;
    static final int GAMEPAD_BUTTON_RIGHT_THUMB = 10;
    static final int GAMEPAD_BUTTON_DPAD_UP = 11;
    static final int GAMEPAD_BUTTON_DPAD_RIGHT = 12;
    static final int GAMEPAD_BUTTON_DPAD_DOWN = 13;
    static final int GAMEPAD_BUTTON_DPAD_LEFT = 14;
    static final int GAMEPAD_BUTTON_COUNT = 15;

    @IntDef({GAMEPAD_BUTTON_A, GAMEPAD_BUTTON_B, GAMEPAD_BUTTON_X, GAMEPAD_BUTTON_Y,
            GAMEPAD_BUTTON_LEFT_BUMPER, GAMEPAD_BUTTON_RIGHT_BUMPER, GAMEPAD_BUTTON_BACK,
            GAMEPAD_BUTTON_START, GAMEPAD_BUTTON_GUIDE, GAMEPAD_BUTTON_LEFT_THUMB,
            GAMEPAD_BUTTON_RIGHT_THUMB, GAMEPAD_BUTTON_DPAD_UP, GAMEPAD_BUTTON_DPAD_RIGHT,
            GAMEPAD_BUTTON_DPAD_DOWN, GAMEPAD_BUTTON_DPAD_LEFT, GAMEPAD_BUTTON_COUNT})
    @Retention(RetentionPolicy.SOURCE)
    @interface GamepadButton {}

    static final int GAMEPAD_AXIS_LEFT_X = 0;
    static final int GAMEPAD_AXIS_LEFT_Y = 1;
    static final int GAMEPAD_AXIS_RIGHT_X = 2;
    static final int GAMEPAD_AXIS_RIGHT_Y = 3;
    static final int GAMEPAD_AXIS_LEFT_TRIGGER = 4;
    static final int GAMEPAD_AXIS_RIGHT_TRIGGER = 5;
    static final int GAMEPAD_AXIS_COUNT = 6;

    @IntDef({GAMEPAD_AXIS_LEFT_X, GAMEPAD_AXIS_LEFT_Y, GAMEPAD_AXIS_RIGHT_X, GAMEPAD_AXIS_RIGHT_Y,
            GAMEPAD_AXIS_LEFT_TRIGGER, GAMEPAD_AXIS_RIGHT_TRIGGER, GAMEPAD_AXIS_COUNT})
    @Retention(RetentionPolicy.SOURCE)
    @interface GamepadAxis {}

    private NativeKitInputValues() {}
}
