// Generated by tools/generate-android-accessibility-values.py. Do not edit.
package io.nativekit;

final class NativeKitAccessibilityValues {
    static final int ACCESSIBILITY_GROUP = 0;
    static final int ACCESSIBILITY_BUTTON = 1;
    static final int ACCESSIBILITY_CHECKBOX = 2;
    static final int ACCESSIBILITY_RADIO = 3;
    static final int ACCESSIBILITY_TEXT = 4;
    static final int ACCESSIBILITY_TEXT_FIELD = 5;
    static final int ACCESSIBILITY_LINK = 6;
    static final int ACCESSIBILITY_IMAGE = 7;
    static final int ACCESSIBILITY_HEADING = 8;
    static final int ACCESSIBILITY_LIST = 9;
    static final int ACCESSIBILITY_LIST_ITEM = 10;
    static final int ACCESSIBILITY_SLIDER = 11;
    static final int ACCESSIBILITY_SCROLL_AREA = 12;

    static final int ACCESSIBILITY_FOCUSABLE = 1;
    static final int ACCESSIBILITY_FOCUSED = 2;
    static final int ACCESSIBILITY_SELECTED = 4;
    static final int ACCESSIBILITY_CHECKED = 8;
    static final int ACCESSIBILITY_DISABLED = 16;
    static final int ACCESSIBILITY_READ_ONLY = 32;
    static final int ACCESSIBILITY_MULTILINE = 64;
    static final int ACCESSIBILITY_PASSWORD = 128;
    static final int ACCESSIBILITY_EXPANDED = 256;

    static final int ACCESSIBILITY_CAN_ACTIVATE = 1;
    static final int ACCESSIBILITY_CAN_FOCUS = 2;
    static final int ACCESSIBILITY_CAN_SET_VALUE = 4;
    static final int ACCESSIBILITY_CAN_SET_SELECTION = 8;
    static final int ACCESSIBILITY_CAN_INCREMENT = 16;
    static final int ACCESSIBILITY_CAN_DECREMENT = 32;
    static final int ACCESSIBILITY_CAN_SCROLL_FORWARD = 64;
    static final int ACCESSIBILITY_CAN_SCROLL_BACKWARD = 128;
    static final int ACCESSIBILITY_CAN_MOVE_NEXT = 256;
    static final int ACCESSIBILITY_CAN_MOVE_PREVIOUS = 512;

    static final int ACCESSIBILITY_ACTION_ACTIVATE = 1;
    static final int ACCESSIBILITY_ACTION_FOCUS = 2;
    static final int ACCESSIBILITY_ACTION_CLEAR_FOCUS = 3;
    static final int ACCESSIBILITY_ACTION_SET_VALUE = 4;
    static final int ACCESSIBILITY_ACTION_SET_SELECTION = 5;
    static final int ACCESSIBILITY_ACTION_INCREMENT = 6;
    static final int ACCESSIBILITY_ACTION_DECREMENT = 7;
    static final int ACCESSIBILITY_ACTION_SCROLL_FORWARD = 8;
    static final int ACCESSIBILITY_ACTION_SCROLL_BACKWARD = 9;
    static final int ACCESSIBILITY_ACTION_MOVE_NEXT = 10;
    static final int ACCESSIBILITY_ACTION_MOVE_PREVIOUS = 11;

    static final int ACCESSIBILITY_GRANULARITY_CHARACTER = 1;
    static final int ACCESSIBILITY_GRANULARITY_WORD = 2;
    static final int ACCESSIBILITY_GRANULARITY_LINE = 3;
    static final int ACCESSIBILITY_GRANULARITY_PARAGRAPH = 4;
    static final int ACCESSIBILITY_GRANULARITY_PAGE = 5;

    private NativeKitAccessibilityValues() {}
}
