#!/usr/bin/env python3
"""Embed scene-render GLSL templates as portable C++ string constants."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


MODULE_DIR = Path(__file__).resolve().parents[1]
SHADER_DIR = MODULE_DIR / "shaders"
VARIANTS = {
    "gles": ("#version 300 es", "precision highp float;"),
    "gl": ("#version 330", ""),
}
SHADERS = {
    "scene_vertex": ("scene_vertex.glsl", "VERTEX_PRECISION"),
    "scene_fragment": ("scene_fragment.glsl", "FRAGMENT_PRECISION"),
    "pick_vertex": ("pick_vertex.glsl", "VERTEX_PRECISION"),
    "pick_fragment": ("pick_fragment.glsl", "FRAGMENT_PRECISION"),
}


def generate() -> bytes:
    symbols: list[tuple[str, str]] = []
    for name, (filename, precision_placeholder) in SHADERS.items():
        template = (SHADER_DIR / filename).read_text(encoding="utf-8")
        for variant, (version, precision) in VARIANTS.items():
            source = template.replace("{{VERSION}}", version)
            vertex_precision = precision if precision_placeholder == "VERTEX_PRECISION" else ""
            fragment_precision = (
                "precision mediump float;"
                if precision_placeholder == "FRAGMENT_PRECISION" and variant == "gles"
                else ""
            )
            source = source.replace("{{VERTEX_PRECISION}}", vertex_precision)
            source = source.replace("{{FRAGMENT_PRECISION}}", fragment_precision)
            symbols.append((f"{name}_{variant}", source))

    lines = [
        "// Generated by modules/scene_render/tools/generate-shaders.py; do not edit.",
        "#pragma once",
        "",
        "namespace nkscene::shader_source {",
    ]
    for symbol, source in symbols:
        lines.append(f"inline constexpr char {symbol}[] = {json.dumps(source)};")
    lines.extend(("} // namespace nkscene::shader_source", ""))
    return "\n".join(lines).encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if args.output.read_bytes() != generated:
            raise SystemExit(f"{args.output} is stale; run generate-shaders.py")
        print("NativeKit scene-render shader sources are up to date")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(generated)
    print(f"generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
