set(NKUI_SHADER_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../shaders")
set(NKUI_SHADER_GENERATED_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated")
set(NKUI_SHADER_SOURCE_HEADER "${NKUI_SHADER_GENERATED_DIR}/ui_shader_sources.h")
file(GLOB_RECURSE NKUI_SHADER_SOURCE_FILES CONFIGURE_DEPENDS
    "${NKUI_SHADER_SOURCE_DIR}/glsl410/*.glsl"
    "${NKUI_SHADER_SOURCE_DIR}/glsl300es/*.glsl")

add_custom_command(
    OUTPUT "${NKUI_SHADER_SOURCE_HEADER}"
    COMMAND ${CMAKE_COMMAND} -E make_directory "${NKUI_SHADER_GENERATED_DIR}"
    COMMAND ${CMAKE_COMMAND}
        "-DNKUI_SHADER_SOURCE_DIR=${NKUI_SHADER_SOURCE_DIR}"
        "-DNKUI_SHADER_OUTPUT=${NKUI_SHADER_SOURCE_HEADER}"
        -P "${CMAKE_CURRENT_LIST_DIR}/GenerateUiShaderHeader.cmake"
    DEPENDS ${NKUI_SHADER_SOURCE_FILES} "${CMAKE_CURRENT_LIST_DIR}/GenerateUiShaderHeader.cmake"
    COMMENT "Embedding NativeKit UI GLSL sources"
    VERBATIM)
