set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

find_program(MINGW_C_COMPILER
    NAMES x86_64-w64-mingw32-gcc x86_64-w64-mingw32-gcc-posix REQUIRED)
find_program(MINGW_CXX_COMPILER
    NAMES x86_64-w64-mingw32-g++ x86_64-w64-mingw32-g++-posix REQUIRED)
find_program(MINGW_RC_COMPILER x86_64-w64-mingw32-windres REQUIRED)

set(CMAKE_C_COMPILER "${MINGW_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${MINGW_CXX_COMPILER}")
set(CMAKE_RC_COMPILER "${MINGW_RC_COMPILER}")

set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
