#!/usr/bin/env python3
"""Pin SDL_GameControllerDB and regenerate NativeKit's compact Linux table."""

from __future__ import annotations

import argparse
import json
import pathlib
import urllib.request

DEFAULT_REVISION = "28a856f2b92da8891b161acd0abd64fbf4445d97"
REPOSITORY = "https://github.com/mdqinc/SDL_GameControllerDB"
SUPPORTED_FIELDS = {
    "a",
    "b",
    "x",
    "y",
    "back",
    "start",
    "guide",
    "leftshoulder",
    "rightshoulder",
    "leftstick",
    "rightstick",
    "dpup",
    "dpright",
    "dpdown",
    "dpleft",
    "lefttrigger",
    "righttrigger",
    "leftx",
    "lefty",
    "rightx",
    "righty",
    "platform",
    "type",
    "crc",
}


def download(revision: str, name: str) -> bytes:
    url = f"https://raw.githubusercontent.com/mdqinc/SDL_GameControllerDB/{revision}/{name}"
    with urllib.request.urlopen(url) as response:
        return response.read()


def compact_linux(database: str) -> list[str]:
    mappings: dict[str, str] = {}
    for raw_line in database.splitlines():
        if not raw_line or raw_line.startswith("#"):
            continue
        parts = raw_line.split(",")
        if len(parts) < 3 or len(parts[0]) != 32:
            continue
        fields = [field for field in parts[2:] if ":" in field]
        platform = next(
            (field.split(":", 1)[1] for field in fields if field.startswith("platform:")), ""
        )
        if platform != "Linux":
            continue
        supported = [
            field for field in fields if field.split(":", 1)[0] in SUPPORTED_FIELDS
        ]
        mappings[parts[0].lower()] = ",".join([parts[0].lower(), parts[1], *supported, ""])
    return list(mappings.values())


def generated_header(revision: str, mappings: list[str]) -> str:
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/update_gamepad_db.py from SDL_GameControllerDB.",
        f'inline constexpr const char *nk_builtin_gamepad_database_revision = "{revision}";',
        "inline constexpr const char *nk_builtin_gamepad_mappings[] = {",
    ]
    lines.extend(f"    {json.dumps(mapping)}," for mapping in mappings)
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--revision", default=DEFAULT_REVISION)
    args = parser.parse_args()
    root = pathlib.Path(__file__).resolve().parents[1]
    vendor = root / "vendor" / "SDL_GameControllerDB"
    vendor.mkdir(parents=True, exist_ok=True)

    database = download(args.revision, "gamecontrollerdb.txt")
    license_text = download(args.revision, "LICENSE")
    (vendor / "gamecontrollerdb.txt").write_bytes(database)
    (vendor / "LICENSE").write_bytes(license_text)
    (vendor / "SOURCE.md").write_text(
        f"# SDL_GameControllerDB source\n\n"
        f"Repository: {REPOSITORY}\n\n"
        f"Revision: `{args.revision}`\n\n"
        "`gamecontrollerdb.txt` and `LICENSE` are unmodified upstream files.\n",
        encoding="utf-8",
    )
    mappings = compact_linux(database.decode("utf-8"))
    output = root / "src" / "core" / "gamepad_mappings_generated.hpp"
    output.write_text(generated_header(args.revision, mappings), encoding="utf-8")
    print(f"generated {len(mappings)} Linux mappings from {args.revision}")


if __name__ == "__main__":
    main()
