#!/usr/bin/env python3
"""Generate NativeKit UI shader source variants with sokol-shdc."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile


MODULE_DIR = Path(__file__).resolve().parents[1]
SHADER_DIR = MODULE_DIR / "shaders"
DEFAULT_OUTPUT = MODULE_DIR / "src/render/ui_shader_sources.h"
FAMILIES = {
    "solid": ("solid",),
    "path": ("path",),
    "text": ("text_alpha", "text_sdf", "text_color"),
    "composite": ("composite",),
    "effect": ("effect", "blur", "drop_shadow", "box_shadow", "mask"),
    "surface_mesh": ("surface_mesh",),
}
SLANG_EXTENSIONS = {
    "glsl410": "glsl",
    "glsl300es": "glsl",
    "hlsl5": "hlsl",
    "metal_macos": "metal",
}
STAGES = ("vertex", "fragment")
SLANGS = tuple(SLANG_EXTENSIONS)


def generate(shdc: str) -> bytes:
    symbols: dict[str, str] = {}
    with tempfile.TemporaryDirectory(prefix="nativekit-ui-shaders-") as temp_name:
        temp_dir = Path(temp_name)
        for family, programs in FAMILIES.items():
            prefix = temp_dir / family
            subprocess.run(
                [
                    shdc,
                    "-i",
                    str(SHADER_DIR / f"{family}.glsl"),
                    "-o",
                    str(prefix),
                    f"--slang={':'.join(SLANGS)}",
                    "-f",
                    "bare",
                    "--no-log-cmdline",
                ],
                check=True,
            )

            pattern = re.compile(
                rf"{re.escape(family)}_(?P<program>[a-z0-9_]+)_"
                rf"(?P<slang>{'|'.join(SLANGS)})_"
                rf"(?P<stage>vertex|fragment)\.(?P<extension>glsl|hlsl|metal)"
            )
            found: set[tuple[str, str, str]] = set()
            for path in temp_dir.glob(f"{family}_*"):
                match = pattern.fullmatch(path.name)
                if not match:
                    continue
                program = match.group("program")
                slang = match.group("slang")
                stage = match.group("stage")
                extension = match.group("extension")
                if program not in programs:
                    raise RuntimeError(f"unexpected generated shader: {path.name}")
                if extension != SLANG_EXTENSIONS[slang]:
                    raise RuntimeError(f"unexpected extension in {path.name}")
                key = (program, slang, stage)
                if key in found:
                    raise RuntimeError(f"duplicate generated shader: {path.name}")
                found.add(key)
                source = path.read_text(encoding="utf-8")
                symbol = f"ui_shader_{program}_{slang}_{stage}"
                if symbol in symbols:
                    raise RuntimeError(f"duplicate C++ shader symbol: {symbol}")
                symbols[symbol] = source

            expected = {
                (program, slang, stage)
                for program in programs
                for slang in SLANGS
                for stage in STAGES
            }
            if found != expected:
                missing = sorted(expected - found)
                extra = sorted(found - expected)
                raise RuntimeError(
                    f"incomplete {family} shader output; missing={missing}, extra={extra}"
                )

    lines = [
        "// Generated by modules/ui/tools/generate-shaders.py; do not edit.",
        "#pragma once",
        "",
        "namespace shader_source {",
    ]
    for symbol, source in sorted(symbols.items()):
        lines.append(f"inline constexpr char {symbol}[] = {json.dumps(source)};")
    lines.extend(("} // namespace shader_source", ""))
    return "\n".join(lines).encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--shdc",
        default=os.environ.get("SOKOL_SHDC", "sokol-shdc"),
        help="path to sokol-shdc (default: SOKOL_SHDC or PATH)",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in output differs; do not write it",
    )
    args = parser.parse_args()

    try:
        generated = generate(args.shdc)
    except (OSError, subprocess.CalledProcessError, RuntimeError) as error:
        print(f"shader generation failed: {error}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = args.output.read_bytes()
        except OSError as error:
            print(f"cannot read generated shader header {args.output}: {error}", file=sys.stderr)
            return 1
        if generated != current:
            print(f"{args.output} is stale; run modules/ui/tools/generate-shaders.sh", file=sys.stderr)
            return 1
        print("NativeKit UI shader sources are up to date")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(generated)
    print(f"generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
