#ifndef NATIVEKIT_UI_LAYOUT_H
#define NATIVEKIT_UI_LAYOUT_H

#include "nativekit_ui.h"

#include <stdint.h>

/*
 * This is the NativeKit/Haxe frontend bridge. It is deliberately separate
 * from nativekit_ui.h: the wire format is batched and versioned, but the
 * layout policy is still expected to evolve before becoming stable ABI.
 */

#ifdef __cplusplus
extern "C" {
#endif

enum {
    NKUI_LAYOUT_API_VERSION = 1,
    NKUI_LAYOUT_TRANSACTION_VERSION = 1,
    NKUI_LAYOUT_TRANSACTION_HEADER_BYTES = 16,
    NKUI_LAYOUT_NODE_RECORD_BYTES = 128,
    NKUI_LAYOUT_CLIP_HORIZONTAL = 1u << 0,
    NKUI_LAYOUT_CLIP_VERTICAL = 1u << 1,
    NKUI_LAYOUT_NODE_BOX = 1,
    NKUI_LAYOUT_NODE_TEXT = 2,
    NKUI_LAYOUT_NODE_BUTTON = 3,
    NKUI_LAYOUT_SIZING_FIT = 0,
    NKUI_LAYOUT_SIZING_GROW = 1,
    NKUI_LAYOUT_SIZING_FIXED = 2,
    NKUI_LAYOUT_SIZING_PERCENT = 3,
    NKUI_LAYOUT_DIRECTION_LEFT_TO_RIGHT = 0,
    NKUI_LAYOUT_DIRECTION_TOP_TO_BOTTOM = 1,
    NKUI_LAYOUT_EVENT_BUTTON_ACTIVATED = 1
};

/** Opaque retained layout session used by a Haxe-owned component tree. */
NK_DECLARE_HANDLE(nkui_layout_session);

/** One semantic event produced by the most recently submitted frame. */
typedef struct nkui_layout_event {
    uint32_t kind;
    uint32_t node_id;
} nkui_layout_event;

/** Creates a private layout session. */
NKUI_API nkui_result NK_CALL nkui_layout_session_create(
    nkui_layout_session *out_session NKUI_OUT);

/** Destroys a layout session and releases its retained native frame state. */
NKUI_API nkui_result NK_CALL nkui_layout_session_destroy(nkui_layout_session session);

/** Copies the font collection configuration into the layout session. */
NKUI_API nkui_result NK_CALL nkui_layout_session_set_font_collection(
    nkui_layout_session session, nkui_resource fonts);

/**
 * Submits one flat, Haxe-owned semantic tree transaction.
 *
 * The transaction is little-endian and consists of a 16-byte header, fixed
 * 128-byte node records, and a UTF-8 string table. Node text offsets are
 * absolute byte offsets from the beginning of the transaction. The native
 * side copies all values before returning, so the input buffer may be reused.
 */
NKUI_API nkui_result NK_CALL nkui_layout_session_submit(
    nkui_layout_session session, const uint8_t *transaction NKUI_IN_ARRAY(transaction_bytes),
    uint32_t transaction_bytes, float width, float height, float pointer_x, float pointer_y,
    nk_bool pointer_down, float delta_seconds);

/** Returns the number of events generated by the most recent submission. */
NKUI_API nkui_result NK_CALL nkui_layout_session_get_event_count(
    nkui_layout_session session, uint32_t *out_count NK_OUT);

/** Reads one event from the most recent submission. */
NKUI_API nkui_result NK_CALL nkui_layout_session_get_event(
    nkui_layout_session session, uint32_t index, nkui_layout_event *out_event NK_OUT);

/** Executes the submitted layout through the existing NativeKit renderer. */
NKUI_API nkui_result NK_CALL nkui_layout_session_render_frame(
    nkui_renderer renderer, nkui_layout_session session, nk_handle surface,
    const nkui_frame_info *frame_info);

#ifdef __cplusplus
}
#endif

#endif
