#ifndef NATIVEKIT_UI_LAYOUT_H
#define NATIVEKIT_UI_LAYOUT_H

#include "nativekit_ui.h"

#include <stdint.h>

/*
 * This is the NativeKit/Haxe frontend bridge. It is deliberately separate
 * from nativekit_ui.h: the wire format is batched and versioned, but the
 * layout policy is still expected to evolve before becoming stable ABI.
 */

#ifdef __cplusplus
extern "C" {
#endif

/** Layout bridge and wire-format versions and fixed sizes. */
enum {
    NKUI_LAYOUT_API_VERSION = 3,
    NKUI_LAYOUT_TRANSACTION_VERSION = 2,
    NKUI_LAYOUT_TRANSACTION_HEADER_BYTES = 16,
    NKUI_LAYOUT_NODE_RECORD_BYTES = 160
};

/** Bit flags stored in each node's clip-flags field. */
enum {
    NKUI_LAYOUT_CLIP_HORIZONTAL = 1u << 0,
    NKUI_LAYOUT_CLIP_VERTICAL = 1u << 1
};

/** Node kinds encoded in the transaction. */
enum {
    NKUI_LAYOUT_NODE_BOX = 1,
    NKUI_LAYOUT_NODE_TEXT = 2,
    NKUI_LAYOUT_NODE_BUTTON = 3
};

/** Sizing modes encoded for each node axis. */
enum {
    NKUI_LAYOUT_SIZING_FIT = 0,
    NKUI_LAYOUT_SIZING_GROW = 1,
    NKUI_LAYOUT_SIZING_FIXED = 2,
    NKUI_LAYOUT_SIZING_PERCENT = 3
};

/** Child flow directions encoded in node styles. */
enum {
    NKUI_LAYOUT_DIRECTION_LEFT_TO_RIGHT = 0,
    NKUI_LAYOUT_DIRECTION_TOP_TO_BOTTOM = 1
};

/** Semantic event kinds returned by the layout session. */
enum {
    NKUI_LAYOUT_EVENT_BUTTON_ACTIVATED = 1
};

/** Byte offsets within each fixed-size node record. */
enum {
    NKUI_LAYOUT_NODE_ID_OFFSET = 0,
    NKUI_LAYOUT_NODE_PARENT_OFFSET = 4,
    NKUI_LAYOUT_NODE_KIND_OFFSET = 8,
    NKUI_LAYOUT_NODE_WIDTH_SIZING_OFFSET = 12,
    NKUI_LAYOUT_NODE_WIDTH_VALUE_OFFSET = 16,
    NKUI_LAYOUT_NODE_HEIGHT_SIZING_OFFSET = 20,
    NKUI_LAYOUT_NODE_HEIGHT_VALUE_OFFSET = 24,
    NKUI_LAYOUT_NODE_DIRECTION_OFFSET = 28,
    NKUI_LAYOUT_NODE_PADDING_LEFT_OFFSET = 32,
    NKUI_LAYOUT_NODE_PADDING_RIGHT_OFFSET = 36,
    NKUI_LAYOUT_NODE_PADDING_TOP_OFFSET = 40,
    NKUI_LAYOUT_NODE_PADDING_BOTTOM_OFFSET = 44,
    NKUI_LAYOUT_NODE_CHILD_GAP_OFFSET = 48,
    NKUI_LAYOUT_NODE_BACKGROUND_OFFSET = 52,
    NKUI_LAYOUT_NODE_RADIUS_TOP_LEFT_OFFSET = 68,
    NKUI_LAYOUT_NODE_RADIUS_TOP_RIGHT_OFFSET = 72,
    NKUI_LAYOUT_NODE_RADIUS_BOTTOM_LEFT_OFFSET = 76,
    NKUI_LAYOUT_NODE_RADIUS_BOTTOM_RIGHT_OFFSET = 80,
    NKUI_LAYOUT_NODE_CLIP_FLAGS_OFFSET = 84,
    NKUI_LAYOUT_NODE_TEXT_OFFSET_OFFSET = 88,
    NKUI_LAYOUT_NODE_TEXT_LENGTH_OFFSET = 92,
    NKUI_LAYOUT_NODE_TEXT_COLOR_OFFSET = 96,
    NKUI_LAYOUT_NODE_FONT_FAMILY_OFFSET = 112,
    NKUI_LAYOUT_NODE_FONT_SIZE_OFFSET = 116,
    NKUI_LAYOUT_NODE_LETTER_SPACING_OFFSET = 120,
    NKUI_LAYOUT_NODE_LINE_HEIGHT_OFFSET = 124,
    NKUI_LAYOUT_NODE_TEXT_WRAP_OFFSET = 128,
    NKUI_LAYOUT_NODE_TEXT_ALIGNMENT_OFFSET = 132,
    NKUI_LAYOUT_NODE_TEXT_DIRECTION_OFFSET = 136,
    NKUI_LAYOUT_NODE_TEXT_FLAGS_OFFSET = 140,
    NKUI_LAYOUT_NODE_RESERVED_OFFSET = 144
};

/** Opaque retained layout session used by a Haxe-owned component tree. */
NK_DECLARE_HANDLE(nkui_layout_session);

/** One semantic event produced by the most recently submitted frame. */
typedef struct nkui_layout_event {
    uint32_t kind;
    uint32_t node_id;
} nkui_layout_event;

/** Resolved bounds for one node in the most recently submitted layout. */
typedef struct nkui_layout_item {
    /** Set to sizeof(nkui_layout_item) or a larger compatible size. */
    uint32_t struct_size;
    uint32_t node_id;
    float x;
    float y;
    float width;
    float height;
} nkui_layout_item;

/** Per-submission logical viewport and pointer state. */
typedef struct nkui_layout_frame_input {
    /** Set to sizeof(nkui_layout_frame_input) or a larger compatible size. */
    uint32_t struct_size;
    float width;
    float height;
    float pointer_x;
    float pointer_y;
    nk_bool pointer_down;
    float delta_seconds;
} nkui_layout_frame_input;

/** Creates a private layout session. */
NKUI_API nkui_result NK_CALL nkui_layout_session_create(
    nkui_layout_session *out_session NKUI_OUT);

/** Destroys a layout session and releases its retained native frame state. */
NKUI_API nkui_result NK_CALL nkui_layout_session_destroy(nkui_layout_session session);

/** Copies the font collection configuration into the layout session. */
NKUI_API nkui_result NK_CALL nkui_layout_session_set_font_collection(
    nkui_layout_session session, nkui_resource fonts);

/**
 * Submits one flat, Haxe-owned semantic tree transaction.
 *
 * The transaction is little-endian and consists of a 16-byte header, fixed
 * 160-byte node records, and a UTF-8 string table. Node text offsets are
 * absolute byte offsets from the beginning of the transaction. The native
 * side copies all values before returning, so the input buffer may be reused.
 */
NKUI_API nkui_result NK_CALL nkui_layout_session_submit(
    nkui_layout_session session, const uint8_t *transaction NKUI_IN_ARRAY(transaction_bytes),
    uint32_t transaction_bytes, const nkui_layout_frame_input *frame);

/** Returns the number of events generated by the most recent submission. */
NKUI_API nkui_result NK_CALL nkui_layout_session_get_event_count(
    nkui_layout_session session, uint32_t *out_count NK_OUT);

/** Reads one event from the most recent submission. */
NKUI_API nkui_result NK_CALL nkui_layout_session_get_event(
    nkui_layout_session session, uint32_t index, nkui_layout_event *out_event NK_OUT);

/** Returns resolved bounds for a node from the most recent submission. */
NKUI_API nkui_result NK_CALL nkui_layout_session_get_item(
    nkui_layout_session session, uint32_t node_id, nkui_layout_item *out_item NK_INOUT);

/** Executes the submitted layout through the existing NativeKit renderer.
 *
 * When load_existing is non-zero, the layout is composited over the current
 * surface contents instead of clearing the frame first.
 */
NKUI_API nkui_result NK_CALL nkui_layout_session_render_frame(
    nkui_renderer renderer, nkui_layout_session session, nk_handle surface,
    const nkui_frame_info *frame_info, nk_bool load_existing);

#ifdef __cplusplus
}
#endif

#endif
