#!/usr/bin/env python3
"""Generate Android JNI input constants from NativeKit's public C enums."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "android/nativekit/src/main/java/io/nativekit/NativeKitInputValues.java"
GROUPS = (
    ("InputAction", "include/nativekit_input.h", "NK_INPUT_RELEASE", False),
    ("Modifiers", "include/nativekit_input.h", "NK_MOD_SHIFT", True),
    ("Key", "include/nativekit_input.h", "NK_KEY_UNKNOWN", False),
    ("PointerButton", "include/nativekit_input.h", "NK_POINTER_BUTTON_LEFT", False),
    ("TouchAction", "include/nativekit_input.h", "NK_TOUCH_BEGIN", False),
    ("TouchTool", "include/nativekit_input.h", "NK_TOUCH_TOOL_FINGER", False),
    ("GamepadButton", "include/nativekit_gamepad.h", "NK_GAMEPAD_BUTTON_A", False),
    ("GamepadAxis", "include/nativekit_gamepad.h", "NK_GAMEPAD_AXIS_LEFT_X", False),
)


def enum_groups(path: Path) -> dict[str, list[tuple[str, int]]]:
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", path.read_text(), flags=re.S)
    result: dict[str, list[tuple[str, int]]] = {}
    values: dict[str, int] = {}
    for match in re.finditer(r"enum\s*\{(.*?)\};", source, flags=re.S):
        entries: list[tuple[str, int]] = []
        previous = -1
        for raw in match.group(1).split(","):
            item = raw.strip()
            if not item:
                continue
            name, separator, expression = item.partition("=")
            name = name.strip()
            if not re.fullmatch(r"NK_[A-Z0-9_]+", name):
                continue
            if separator:
                cleaned = re.sub(r"(?<=\d)[uUlL]+\b", "", expression.strip())
                previous = int(eval(cleaned, {"__builtins__": {}}, values))
            else:
                previous += 1
            values[name] = previous
            entries.append((name, previous))
        if entries:
            result[entries[0][0]] = entries
    return result


def java_name(c_name: str) -> str:
    return c_name.removeprefix("NK_")


def render() -> str:
    parsed: dict[Path, dict[str, list[tuple[str, int]]]] = {}
    lines = [
        "// Generated by tools/generate-android-input-values.py. Do not edit.",
        "package io.nativekit;",
        "",
        "import androidx.annotation.IntDef;",
        "import java.lang.annotation.Retention;",
        "import java.lang.annotation.RetentionPolicy;",
        "",
        "/** Stable Java names for input values carried across JNI. */",
        "final class NativeKitInputValues {",
    ]
    for annotation, relative, first, flags in GROUPS:
        path = ROOT / relative
        groups = parsed.setdefault(path, enum_groups(path))
        entries = groups.get(first)
        if not entries:
            raise RuntimeError(f"could not find enum beginning with {first} in {relative}")
        for name, value in entries:
            lines.append(f"    static final int {java_name(name)} = {value};")
        lines.append("")
        names = ", ".join(java_name(name) for name, _ in entries)
        prefix = "    @IntDef(flag = true, value = {" if flags else "    @IntDef({"
        wrapped: list[str] = []
        current = prefix
        for name in names.split(", "):
            suffix = name if current.endswith("{") else ", " + name
            if len(current) + len(suffix) + 2 > 100:
                wrapped.append(current + ",")
                current = "            " + name
            else:
                current += suffix
        wrapped.append(current + "})")
        lines.extend(wrapped)
        lines.extend(("    @Retention(RetentionPolicy.SOURCE)",
                      f"    @interface {annotation} {{}}", ""))
    lines.extend(("    private NativeKitInputValues() {}", "}", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run {Path(__file__).name}")
            return 1
        return 0
    OUTPUT.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
