#!/usr/bin/env python3
"""Generate Android accessibility protocol constants from the public C enums."""

from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "include/nativekit_accessibility.h"
OUTPUT = ROOT / "android/nativekit/src/main/java/io/nativekit/NativeKitAccessibilityValues.java"
PREFIXES = ("NK_ACCESSIBILITY_GROUP", "NK_ACCESSIBILITY_FOCUSABLE",
            "NK_ACCESSIBILITY_CAN_ACTIVATE", "NK_ACCESSIBILITY_ACTION_ACTIVATE",
            "NK_ACCESSIBILITY_GRANULARITY_CHARACTER")


def render() -> str:
    source = re.sub(r"/\*.*?\*/|//[^\n]*", "", HEADER.read_text(), flags=re.S)
    groups = []
    values = {}
    for match in re.finditer(r"enum\s*\{(.*?)\};", source, flags=re.S):
        entries = []
        previous = -1
        for raw in match.group(1).split(","):
            name, separator, expression = raw.strip().partition("=")
            name = name.strip()
            if not re.fullmatch(r"NK_[A-Z0-9_]+", name):
                continue
            if separator:
                cleaned = re.sub(r"(?<=[0-9a-fA-F])[uUlL]+\b", "", expression.strip())
                previous = int(eval(cleaned, {"__builtins__": {}}, values))
            else:
                previous += 1
            values[name] = previous
            entries.append((name, previous))
        if entries and entries[0][0] in PREFIXES:
            groups.append(entries)
    lines = ["// Generated by tools/generate-android-accessibility-values.py. Do not edit.",
             "package io.nativekit;", "", "final class NativeKitAccessibilityValues {"]
    for entries in groups:
        lines.extend(f"    static final int {name.removeprefix('NK_')} = {value};"
                     for name, value in entries)
        lines.append("")
    lines.extend(("    private NativeKitAccessibilityValues() {}", "}", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is stale")
            return 1
        return 0
    OUTPUT.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
